# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#


# NOTE: This is not the way a Kafka cluster would normally be deployed in production, as it is not secure
# and is not fault tolerant. This example is a toy deployment that is only meant to exercise the Kafka code path
# of the ordering service.

version: '2'

networks:
  byfn:

services:
  zookeeper0.example.com:
    container_name: zookeeper0.example.com
    extends:
      file: base/kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888      
    networks:
    - byfn

  zookeeper1.example.com:
    container_name: zookeeper1.example.com
    extends:
      file: base/kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
    ports:
      - 12181:2181
      - 12888:2888
      - 13888:3888      
    networks:
    - byfn

  zookeeper2.example.com:
    container_name: zookeeper2.example.com
    extends:
      file: base/kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
    ports:
      - 22181:2181
      - 22888:2888
      - 23888:3888      
    networks:
    - byfn      

  kafka0.example.com:
    container_name: kafka0.example.com
    extends:
      file: base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
    ports:
      - 9092:9092
      - 9093:9093      
    networks:
    - byfn
    depends_on:
      - zookeeper0.example.com
      - zookeeper1.example.com
      - zookeeper2.example.com    

  kafka3.example.com:
    container_name: kafka3.example.com
    extends:
      file: base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
    ports:
      - 10092:9092
      - 10093:9093   
    networks:
    - byfn
    depends_on:
      - zookeeper0.example.com
      - zookeeper1.example.com
      - zookeeper2.example.com

  kafka2.example.com:
    container_name: kafka2.example.com
    extends:
      file: base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
    ports:
      - 11092:9092
      - 11093:9093
    networks:
    - byfn
    depends_on:
      - zookeeper0.example.com
      - zookeeper1.example.com
      - zookeeper2.example.com

  kafka3.example.com:
    container_name: kafka3.example.com
    extends:
      file: base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
    ports:
      - 12092:9092
      - 12093:9093 
    networks:
    - byfn        
    depends_on:
      - zookeeper0.example.com
      - zookeeper1.example.com
      - zookeeper2.example.com